### ISSUE TITLE
web-studio installation is failing on Ubuntu

### ISSUE THREAD

**Issue by jsuryakt** [ExperitestOfficial/ansible-role-web-studio#20]
https://github.com/ExperitestOfficial/ansible-role-web-studio/blob/75d29aa37fa3cb51d3c11c129306882fa33b978a/tasks/debian-prerequisite.yml#L7

Error :-
task path: /var/lib/jenkins/.ansible/roles/web-studio/tasks/debian-prerequisite.yml:3
11:16:43 META: noop
11:16:44 failed: [mastercloud.experitest.com] (item=[u'rsync', u'unzip', u'psmisc']) => {"ansible_loop_var": "item", "changed": false, "item": ["rsync", "unzip", "psmisc"], "msg": "Unsupported parameters for (apt) module: lock_timeout Supported parameters include: allow_unauthenticated, autoclean, autoremove, cache_valid_time, deb, default_release, dpkg_options, force, force_apt_get, install_recommends, only_upgrade, package, policy_rc_d, purge, state, update_cache, upgrade"}

Possible reasons
lock_timeout is not supported on apt

**Comment by jsuryakt** [comment]
@OmprakashPaliwal @prahastakumar @dikla123

**Comment by prahastakumar** [comment]
@jsuryakt The error indicates you are using ansible version is < 2.9. Please use with ansible 2.13.
@eyalneumann Can you help @jsuryakt here.
